title: Brabusz
default_lang: hu
author:
  name: 'Szabó Márk'
  email: markusz996@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Brabusz személyszállítás'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
